---
- name: install percona-server
  homebrew:
    name: percona-server
    state: present
  notify: restart percona-server
  tags: setup

- name: "install packages"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - sqlite
  tags: setup

#- name: configure percona-server
#  template:
#    dest: "{{ webdev_homebrew_rootpath }}etc/my.cnf"
#    src: 'my.cnf.j2'
#    owner: "{{ user }}"
#  notify: restart percona-serverbrew
#  tags: setup

- name: set permissions
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ webdev_user }}"
    group: "{{ webdev_group }}"
    mode: u=rwX,g=rwX,o=rX
    recurse: yes
  with_items:
    - /usr/local/var/mysql/
  tags: setup

- name: create symlink for LaunchDaemon
  file:
    path: "/Library/LaunchDaemons/homebrew.mxcl.percona-server.plist"
    state: link
    src: "/usr/local/opt/percona-server/homebrew.mxcl.percona-server.plist"
  become: true
  notify: restart percona-server
  tags: setup

- name: install MySQL-python
  pip:
    name: MySQL-python
  tags: setup

- name: create instance
  include: create_instance.yml
  when: name is defined
