---
- name: unlink all PHP versions
  shell: "brew list -1 | egrep 'php[0-9]{2}$' | while read V; do brew unlink $V; done"
  tags: setup

- name: "PHP {{ version }}: install "
  homebrew:
    name: "{{ webdev_php_versions[version].package }}"
    state: present
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: link"
  homebrew:
    name: "{{ webdev_php_versions[version].package }}"
    state: linked
  tags: setup

- name: "PHP {{ version }}: install extensions"
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ webdev_php_versions[version].extension_packages }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: configure php-fpm"
  template:
    dest: "{{ webdev_homebrew_rootpath }}etc/php/{{ version }}/php-fpm.conf"
    src: "php{{ version | replace('.', '') }}/php-fpm.conf.j2"
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: add additional configuration for php-fpm"
  copy:
    dest: "{{ webdev_homebrew_rootpath }}etc/php/{{ version }}/conf.d/"
    src: "php{{ version | replace('.', '') }}/conf.d/"
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: remove default configuration folder"
  file:
    path: "{{ webdev_homebrew_rootpath }}etc/php/{{ version }}/php-fpm.d"
    state: absent
  tags: setup

- name: "PHP {{ version }}: create configuration folders for php-fpm pools"
  file:
    path: "{{ webdev_homebrew_rootpath }}etc/php/{{ version }}/fpm.d"
    state: directory
    owner: "{{ webdev_php_user }}"
    group: "{{ webdev_php_group }}"
  notify: restart php-fpm
  tags: setup

- name: "PHP {{ version }}: create symlink for LaunchDaemon"
  file:
    path: "/Library/LaunchDaemons/homebrew.mxcl.{{ webdev_php_versions[version].package }}.plist"
    state: link
    src: "/usr/local/opt/{{ webdev_php_versions[version].package }}/homebrew.mxcl.{{ webdev_php_versions[version].package }}.plist"
  become: true
  notify: restart php-fpm
  tags: setup
