---
- name: install npm
  homebrew:
    name: npm
    state: present

- name: install grunt, gulp, yo, bower
  npm:
    name: "{{ item }}"
    state: latest
    global: yes
  with_items:
    - grunt-cli
    - gulp
    - yo
    - bower

- name: install compass
  gem:
    name: compass
    state: latest
    user_install: no
  become: true
